const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const path=require('path');
const dir=path.join(__dirname,'../browser_extension');
vm.runInThisContext(fs.readFileSync(path.join(dir,'image_match.js'),'utf8')+'\nglobalThis.IM=ImageMatch;');
(async()=>{
    const now=Date.now(), seed='test-random-seed';
    const rows=await IM.snapshot([['김테스트','900101-1234567','4111-2222-3333-4444','테스트영업부','서울특별시']],seed,now);
    const ocr=JSON.parse(fs.readFileSync(path.join(__dirname,'ocr_fixture_result.json'),'utf8'));
    assert.equal((await IM.match(ocr.lines,rows,seed,now)).status,'blocked');
    assert.equal((await IM.match(['4111 2222 3333 4444'],rows,seed,now)).status,'blocked');
    assert.equal((await IM.match(['김테스트 테스트영업부 서울특별시'],rows,seed,now)).status,'blocked');
    assert.equal((await IM.match(['김테스트 서울특별시'],rows,seed,now)).status,'allow');
    assert.equal((await IM.match(['오늘 점심은 비빔밥입니다'],rows,seed,now)).status,'allow');
    assert.equal((await IM.match([''],rows,seed,now)).status,'hold');
    assert.equal((await IM.match(ocr.lines,[],seed,now)).error,'DB_BASELINE_MISSING');
    assert.equal((await IM.match(ocr.lines,rows,seed,now+IM.TTL)).status,'hold');
    assert.equal((await IM.match(['4111 2222 3333 4445'],rows,seed,now)).status,'allow');
    assert.equal((await IM.match(ocr.lines,rows,'other-seed',now)).status,'allow');
    assert(!JSON.stringify(rows).includes('김테스트'));
    assert(!JSON.stringify(rows).includes('4111'));
    assert(IM.isAI('chatgpt.com'));assert(!IM.isAI('chatgpt.com.evil.invalid'));
    assert(!IM.isAI('example.com'));
    console.log('PASS: 15 OCR matching, baseline expiry, privacy and domain cases.');
})().catch(e=>{console.error(e);process.exitCode=1});
